/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Light adjustments for Node.js */
export interface JsLightAdjustments {
  exposure: number
  contrast: number
  highlights: number
  shadows: number
  whites: number
  blacks: number
}
/** Color adjustments for Node.js */
export interface JsColorAdjustments {
  temperature: number
  tint: number
  saturation: number
  vibrance: number
}
/** Combined adjustments for Node.js */
export interface JsAdjustments {
  light: JsLightAdjustments
  color: JsColorAdjustments
}
/** Histogram result for Node.js */
export interface JsHistogram {
  r: Array<number>
  g: Array<number>
  b: Array<number>
  lum: Array<number>
}
/** Perceptual hash result for Node.js */
export interface JsPHash {
  hash: string
  bits: number
}
/** Generate dHash from a file path */
export declare function generateDhashFromFile(path: string): string
/** Calculate hamming distance between two hex hashes */
export declare function calculateHammingDistance(hash1: string, hash2: string): number
/** Check if two images are duplicates based on dHash */
export declare function areDuplicates(hash1: string, hash2: string, threshold?: number | undefined | null): boolean
/** Apply adjustments to a raw RGBA buffer */
export declare function applyAdjustmentsToBuffer(buffer: Buffer, width: number, height: number, adjustments: JsAdjustments): Buffer
/** Generate histogram from raw RGBA buffer */
export declare function generateHistogramFromBuffer(buffer: Buffer): JsHistogram
/** Native image processor wrapper for Node.js */
export declare class NativeImageProcessor {
  /** Create a new image processor */
  constructor()
  /** Load an image from a file path */
  load(path: string): void
  /** Check if an image is loaded */
  isLoaded(): boolean
  /** Get image dimensions */
  dimensions(): Array<number> | null
  /** Process image with adjustments and return RGBA buffer */
  process(adjustments: JsAdjustments): Buffer
  /** Generate histogram from processed image */
  histogram(adjustments: JsAdjustments): JsHistogram
  /** Generate perceptual hash */
  phash(): JsPHash
  /** Generate dHash (JS-compatible 64-bit hex hash) */
  dhash(): string
  /** Get original image as RGBA buffer */
  originalRgba(): Buffer
}
